/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface EIP1967ProxyInterface extends utils.Interface {
  functions: {};

  events: {
    "ProxyImplementationUpdated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProxyImplementationUpdated"): EventFragment;
}

export type ProxyImplementationUpdatedEvent = TypedEvent<
  [string, string],
  { previousImplementation: string; newImplementation: string }
>;

export type ProxyImplementationUpdatedEventFilter =
  TypedEventFilter<ProxyImplementationUpdatedEvent>;

export interface EIP1967Proxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EIP1967ProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "ProxyImplementationUpdated(address,address)"(
      previousImplementation?: string | null,
      newImplementation?: string | null
    ): ProxyImplementationUpdatedEventFilter;
    ProxyImplementationUpdated(
      previousImplementation?: string | null,
      newImplementation?: string | null
    ): ProxyImplementationUpdatedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
