/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IAirdropDistributorV2Interface extends utils.Interface {
  functions: {
    "airdrop(address)": FunctionFragment;
    "airdropList(address[])": FunctionFragment;
    "airdropPool(uint256)": FunctionFragment;
    "airdropPoolLength()": FunctionFragment;
    "depositKlay(address)": FunctionFragment;
    "depositToken(address,address,uint128)": FunctionFragment;
    "depositedAirdrop(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "airdrop", values: [string]): string;
  encodeFunctionData(
    functionFragment: "airdropList",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "airdropPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "airdropPoolLength",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "depositKlay", values: [string]): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositedAirdrop",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "airdrop", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "airdropList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airdropPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airdropPoolLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositKlay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositedAirdrop",
    data: BytesLike
  ): Result;

  events: {
    "Airdrop(address,address,uint128,uint256,uint256)": EventFragment;
    "Deposit(address,address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Airdrop"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
}

export type AirdropEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  {
    pool: string;
    token: string;
    amount: BigNumber;
    startTime: BigNumber;
    period: BigNumber;
  }
>;

export type AirdropEventFilter = TypedEventFilter<AirdropEvent>;

export type DepositEvent = TypedEvent<
  [string, string, BigNumber, string],
  { pool: string; token: string; amount: BigNumber; depositor: string }
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface IAirdropDistributorV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAirdropDistributorV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    airdrop(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    airdropList(
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    airdropPool(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    airdropPoolLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositKlay(
      pool: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositToken(
      pool: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositedAirdrop(
      pool: string,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[], BigNumber] & {
        tokens: string[];
        amounts: BigNumber[];
        startTime: BigNumber;
      }
    >;
  };

  airdrop(
    pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  airdropList(
    pools: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  airdropPool(idx: BigNumberish, overrides?: CallOverrides): Promise<string>;

  airdropPoolLength(overrides?: CallOverrides): Promise<BigNumber>;

  depositKlay(
    pool: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositToken(
    pool: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositedAirdrop(
    pool: string,
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[], BigNumber] & {
      tokens: string[];
      amounts: BigNumber[];
      startTime: BigNumber;
    }
  >;

  callStatic: {
    airdrop(pool: string, overrides?: CallOverrides): Promise<void>;

    airdropList(pools: string[], overrides?: CallOverrides): Promise<void>;

    airdropPool(idx: BigNumberish, overrides?: CallOverrides): Promise<string>;

    airdropPoolLength(overrides?: CallOverrides): Promise<BigNumber>;

    depositKlay(pool: string, overrides?: CallOverrides): Promise<void>;

    depositToken(
      pool: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositedAirdrop(
      pool: string,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[], BigNumber] & {
        tokens: string[];
        amounts: BigNumber[];
        startTime: BigNumber;
      }
    >;
  };

  filters: {
    "Airdrop(address,address,uint128,uint256,uint256)"(
      pool?: string | null,
      token?: null,
      amount?: null,
      startTime?: null,
      period?: null
    ): AirdropEventFilter;
    Airdrop(
      pool?: string | null,
      token?: null,
      amount?: null,
      startTime?: null,
      period?: null
    ): AirdropEventFilter;

    "Deposit(address,address,uint256,address)"(
      pool?: string | null,
      token?: null,
      amount?: null,
      depositor?: null
    ): DepositEventFilter;
    Deposit(
      pool?: string | null,
      token?: null,
      amount?: null,
      depositor?: null
    ): DepositEventFilter;
  };

  estimateGas: {
    airdrop(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    airdropList(
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    airdropPool(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    airdropPoolLength(overrides?: CallOverrides): Promise<BigNumber>;

    depositKlay(
      pool: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositToken(
      pool: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositedAirdrop(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    airdrop(
      pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    airdropList(
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    airdropPool(
      idx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    airdropPoolLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositKlay(
      pool: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositToken(
      pool: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositedAirdrop(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
