/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type MintParamsStruct = {
  lowerOld: BigNumberish;
  lower: BigNumberish;
  upperOld: BigNumberish;
  upper: BigNumberish;
  amount0Desired: BigNumberish;
  amount1Desired: BigNumberish;
};

export type MintParamsStructOutput = [
  number,
  number,
  number,
  number,
  BigNumber,
  BigNumber
] & {
  lowerOld: number;
  lower: number;
  upperOld: number;
  upper: number;
  amount0Desired: BigNumber;
  amount1Desired: BigNumber;
};

export type PositionStruct = {
  liquidity: BigNumberish;
  feeGrowthInside0Last: BigNumberish;
  feeGrowthInside1Last: BigNumberish;
  feeOwed0: BigNumberish;
  feeOwed1: BigNumberish;
};

export type PositionStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  liquidity: BigNumber;
  feeGrowthInside0Last: BigNumber;
  feeGrowthInside1Last: BigNumber;
  feeOwed0: BigNumber;
  feeOwed1: BigNumber;
};

export type TickStruct = {
  previousTick: BigNumberish;
  nextTick: BigNumberish;
  liquidity: BigNumberish;
  feeGrowthOutside0: BigNumberish;
  feeGrowthOutside1: BigNumberish;
  secondsGrowthOutside: BigNumberish;
};

export type TickStructOutput = [
  number,
  number,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  previousTick: number;
  nextTick: number;
  liquidity: BigNumber;
  feeGrowthOutside0: BigNumber;
  feeGrowthOutside1: BigNumber;
  secondsGrowthOutside: BigNumber;
};

export interface IConcentratedLiquidityPoolInterface extends utils.Interface {
  functions: {
    "burn(int24,int24,uint128)": FunctionFragment;
    "collect(int24,int24,uint256,uint256)": FunctionFragment;
    "collectProtocolFee()": FunctionFragment;
    "factory()": FunctionFragment;
    "feeGrowthGlobal0()": FunctionFragment;
    "feeGrowthGlobal1()": FunctionFragment;
    "flash(address,uint256,uint256,bytes)": FunctionFragment;
    "getAssets()": FunctionFragment;
    "getImmutables()": FunctionFragment;
    "getPriceAndNearestTicks()": FunctionFragment;
    "getReserves()": FunctionFragment;
    "getSecondsGrowthAndLastObservation()": FunctionFragment;
    "liquidity()": FunctionFragment;
    "mint((int24,int24,int24,int24,uint128,uint128))": FunctionFragment;
    "nearestTick()": FunctionFragment;
    "positions(address,int24,int24)": FunctionFragment;
    "price()": FunctionFragment;
    "rangeFeeGrowth(int24,int24)": FunctionFragment;
    "swap(bytes)": FunctionFragment;
    "swapFee()": FunctionFragment;
    "swapFeeGrowthGlobal0()": FunctionFragment;
    "swapFeeGrowthGlobal1()": FunctionFragment;
    "tickSpacing()": FunctionFragment;
    "ticks(int24)": FunctionFragment;
    "token0()": FunctionFragment;
    "token1()": FunctionFragment;
    "totalTicks()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "burn",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collect",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectProtocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeGrowthGlobal0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeGrowthGlobal1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flash",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getAssets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getImmutables",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceAndNearestTicks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSecondsGrowthAndLastObservation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "liquidity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [MintParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "nearestTick",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "price", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rangeFeeGrowth",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "swap", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "swapFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapFeeGrowthGlobal0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapFeeGrowthGlobal1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tickSpacing",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ticks", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalTicks",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "collect", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeGrowthGlobal0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeGrowthGlobal1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAssets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getImmutables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceAndNearestTicks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecondsGrowthAndLastObservation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nearestTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "price", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rangeFeeGrowth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapFeeGrowthGlobal0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapFeeGrowthGlobal1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tickSpacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ticks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalTicks", data: BytesLike): Result;

  events: {};
}

export interface IConcentratedLiquidityPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IConcentratedLiquidityPoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    burn(
      lower: BigNumberish,
      upper: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    collect(
      lower: BigNumberish,
      upper: BigNumberish,
      desiredToken0Fees: BigNumberish,
      desiredToken1Fees: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    collectProtocolFee(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    feeGrowthGlobal0(overrides?: CallOverrides): Promise<[BigNumber]>;

    feeGrowthGlobal1(overrides?: CallOverrides): Promise<[BigNumber]>;

    flash(
      recipient: string,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAssets(
      overrides?: CallOverrides
    ): Promise<[string[]] & { tokens: string[] }>;

    getImmutables(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string, string, string, string] & {
        MAX_TICK_LIQUIDITY: BigNumber;
        tickSpacing: number;
        swapFee: number;
        factory: string;
        masterDeployer: string;
        token0: string;
        token1: string;
      }
    >;

    getPriceAndNearestTicks(
      overrides?: CallOverrides
    ): Promise<[BigNumber, number] & { price: BigNumber; nearestTick: number }>;

    getReserves(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserve0: BigNumber; reserve1: BigNumber }
    >;

    getSecondsGrowthAndLastObservation(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & {
        secondGrowthGlobal: BigNumber;
        lastObservation: number;
      }
    >;

    liquidity(overrides?: CallOverrides): Promise<[BigNumber]>;

    mint(
      data: MintParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nearestTick(overrides?: CallOverrides): Promise<[number]>;

    positions(
      owner: string,
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[PositionStructOutput]>;

    price(overrides?: CallOverrides): Promise<[BigNumber]>;

    rangeFeeGrowth(
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        feeGrowthInside0: BigNumber;
        feeGrowthInside1: BigNumber;
      }
    >;

    swap(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapFee(overrides?: CallOverrides): Promise<[number]>;

    swapFeeGrowthGlobal0(overrides?: CallOverrides): Promise<[BigNumber]>;

    swapFeeGrowthGlobal1(overrides?: CallOverrides): Promise<[BigNumber]>;

    tickSpacing(overrides?: CallOverrides): Promise<[number]>;

    ticks(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[TickStructOutput]>;

    token0(overrides?: CallOverrides): Promise<[string]>;

    token1(overrides?: CallOverrides): Promise<[string]>;

    totalTicks(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  burn(
    lower: BigNumberish,
    upper: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  collect(
    lower: BigNumberish,
    upper: BigNumberish,
    desiredToken0Fees: BigNumberish,
    desiredToken1Fees: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  collectProtocolFee(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  feeGrowthGlobal0(overrides?: CallOverrides): Promise<BigNumber>;

  feeGrowthGlobal1(overrides?: CallOverrides): Promise<BigNumber>;

  flash(
    recipient: string,
    amount0: BigNumberish,
    amount1: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAssets(overrides?: CallOverrides): Promise<string[]>;

  getImmutables(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, number, string, string, string, string] & {
      MAX_TICK_LIQUIDITY: BigNumber;
      tickSpacing: number;
      swapFee: number;
      factory: string;
      masterDeployer: string;
      token0: string;
      token1: string;
    }
  >;

  getPriceAndNearestTicks(
    overrides?: CallOverrides
  ): Promise<[BigNumber, number] & { price: BigNumber; nearestTick: number }>;

  getReserves(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { reserve0: BigNumber; reserve1: BigNumber }
  >;

  getSecondsGrowthAndLastObservation(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number] & {
      secondGrowthGlobal: BigNumber;
      lastObservation: number;
    }
  >;

  liquidity(overrides?: CallOverrides): Promise<BigNumber>;

  mint(
    data: MintParamsStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nearestTick(overrides?: CallOverrides): Promise<number>;

  positions(
    owner: string,
    lower: BigNumberish,
    upper: BigNumberish,
    overrides?: CallOverrides
  ): Promise<PositionStructOutput>;

  price(overrides?: CallOverrides): Promise<BigNumber>;

  rangeFeeGrowth(
    lower: BigNumberish,
    upper: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      feeGrowthInside0: BigNumber;
      feeGrowthInside1: BigNumber;
    }
  >;

  swap(
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapFee(overrides?: CallOverrides): Promise<number>;

  swapFeeGrowthGlobal0(overrides?: CallOverrides): Promise<BigNumber>;

  swapFeeGrowthGlobal1(overrides?: CallOverrides): Promise<BigNumber>;

  tickSpacing(overrides?: CallOverrides): Promise<number>;

  ticks(
    tick: BigNumberish,
    overrides?: CallOverrides
  ): Promise<TickStructOutput>;

  token0(overrides?: CallOverrides): Promise<string>;

  token1(overrides?: CallOverrides): Promise<string>;

  totalTicks(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    burn(
      lower: BigNumberish,
      upper: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        token0Amount: BigNumber;
        token1Amount: BigNumber;
      }
    >;

    collect(
      lower: BigNumberish,
      upper: BigNumberish,
      desiredToken0Fees: BigNumberish,
      desiredToken1Fees: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { token0Fees: BigNumber; token1Fees: BigNumber }
    >;

    collectProtocolFee(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    factory(overrides?: CallOverrides): Promise<string>;

    feeGrowthGlobal0(overrides?: CallOverrides): Promise<BigNumber>;

    feeGrowthGlobal1(overrides?: CallOverrides): Promise<BigNumber>;

    flash(
      recipient: string,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getAssets(overrides?: CallOverrides): Promise<string[]>;

    getImmutables(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string, string, string, string] & {
        MAX_TICK_LIQUIDITY: BigNumber;
        tickSpacing: number;
        swapFee: number;
        factory: string;
        masterDeployer: string;
        token0: string;
        token1: string;
      }
    >;

    getPriceAndNearestTicks(
      overrides?: CallOverrides
    ): Promise<[BigNumber, number] & { price: BigNumber; nearestTick: number }>;

    getReserves(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserve0: BigNumber; reserve1: BigNumber }
    >;

    getSecondsGrowthAndLastObservation(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & {
        secondGrowthGlobal: BigNumber;
        lastObservation: number;
      }
    >;

    liquidity(overrides?: CallOverrides): Promise<BigNumber>;

    mint(data: MintParamsStruct, overrides?: CallOverrides): Promise<BigNumber>;

    nearestTick(overrides?: CallOverrides): Promise<number>;

    positions(
      owner: string,
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PositionStructOutput>;

    price(overrides?: CallOverrides): Promise<BigNumber>;

    rangeFeeGrowth(
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        feeGrowthInside0: BigNumber;
        feeGrowthInside1: BigNumber;
      }
    >;

    swap(data: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    swapFee(overrides?: CallOverrides): Promise<number>;

    swapFeeGrowthGlobal0(overrides?: CallOverrides): Promise<BigNumber>;

    swapFeeGrowthGlobal1(overrides?: CallOverrides): Promise<BigNumber>;

    tickSpacing(overrides?: CallOverrides): Promise<number>;

    ticks(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<TickStructOutput>;

    token0(overrides?: CallOverrides): Promise<string>;

    token1(overrides?: CallOverrides): Promise<string>;

    totalTicks(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    burn(
      lower: BigNumberish,
      upper: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    collect(
      lower: BigNumberish,
      upper: BigNumberish,
      desiredToken0Fees: BigNumberish,
      desiredToken1Fees: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    collectProtocolFee(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    feeGrowthGlobal0(overrides?: CallOverrides): Promise<BigNumber>;

    feeGrowthGlobal1(overrides?: CallOverrides): Promise<BigNumber>;

    flash(
      recipient: string,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAssets(overrides?: CallOverrides): Promise<BigNumber>;

    getImmutables(overrides?: CallOverrides): Promise<BigNumber>;

    getPriceAndNearestTicks(overrides?: CallOverrides): Promise<BigNumber>;

    getReserves(overrides?: CallOverrides): Promise<BigNumber>;

    getSecondsGrowthAndLastObservation(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidity(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      data: MintParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nearestTick(overrides?: CallOverrides): Promise<BigNumber>;

    positions(
      owner: string,
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    price(overrides?: CallOverrides): Promise<BigNumber>;

    rangeFeeGrowth(
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swap(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapFee(overrides?: CallOverrides): Promise<BigNumber>;

    swapFeeGrowthGlobal0(overrides?: CallOverrides): Promise<BigNumber>;

    swapFeeGrowthGlobal1(overrides?: CallOverrides): Promise<BigNumber>;

    tickSpacing(overrides?: CallOverrides): Promise<BigNumber>;

    ticks(tick: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    token0(overrides?: CallOverrides): Promise<BigNumber>;

    token1(overrides?: CallOverrides): Promise<BigNumber>;

    totalTicks(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    burn(
      lower: BigNumberish,
      upper: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    collect(
      lower: BigNumberish,
      upper: BigNumberish,
      desiredToken0Fees: BigNumberish,
      desiredToken1Fees: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    collectProtocolFee(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeGrowthGlobal0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeGrowthGlobal1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flash(
      recipient: string,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAssets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getImmutables(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPriceAndNearestTicks(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReserves(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSecondsGrowthAndLastObservation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mint(
      data: MintParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nearestTick(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    positions(
      owner: string,
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    price(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rangeFeeGrowth(
      lower: BigNumberish,
      upper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swap(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapFeeGrowthGlobal0(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapFeeGrowthGlobal1(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tickSpacing(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ticks(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalTicks(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
