/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPoolFlashCallback,
  IPoolFlashCallbackInterface,
} from "../IPoolFlashCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fee0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fee1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "flashCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPoolFlashCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolFlashCallbackInterface {
    return new utils.Interface(_abi) as IPoolFlashCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolFlashCallback {
    return new Contract(address, _abi, signerOrProvider) as IPoolFlashCallback;
  }
}
