/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IProtocolFeePool,
  IProtocolFeePoolInterface,
} from "../IProtocolFeePool";

const _abi = [
  {
    inputs: [],
    name: "collectProtocolFee",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenProtocolFees",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IProtocolFeePool__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolFeePoolInterface {
    return new utils.Interface(_abi) as IProtocolFeePoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProtocolFeePool {
    return new Contract(address, _abi, signerOrProvider) as IProtocolFeePool;
  }
}
