/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  LPRewardCallee,
  LPRewardCalleeInterface,
} from "../LPRewardCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint128",
        name: "airdrop0",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "airdrop1",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "reward",
        type: "uint128",
      },
      {
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "period",
        type: "uint256",
      },
    ],
    name: "depositAirdropAndReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rewardToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class LPRewardCallee__factory {
  static readonly abi = _abi;
  static createInterface(): LPRewardCalleeInterface {
    return new utils.Interface(_abi) as LPRewardCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LPRewardCallee {
    return new Contract(address, _abi, signerOrProvider) as LPRewardCallee;
  }
}
