/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  PangeaBatchable,
  PangeaBatchableInterface,
} from "../PangeaBatchable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class PangeaBatchable__factory {
  static readonly abi = _abi;
  static createInterface(): PangeaBatchableInterface {
    return new utils.Interface(_abi) as PangeaBatchableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PangeaBatchable {
    return new Contract(address, _abi, signerOrProvider) as PangeaBatchable;
  }
}
